project:
  type: website
  output-dir: _site

resources:
  - decisions/attachments

website:
  site-url: https://fire.github.io/manuals
  repo-url: https://github.com/fire/manuals
  repo-branch: main
  repo-actions: edit
  title: Chibifire — Manuals
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Changes"
        file: changelog.qmd
      - text: "Decisions"
        file: decisions.qmd
      - text: "References"
        file: references.qmd
      - text: "Build"
        file: build-info.qmd
  page-footer:
    right:
      - icon: github
        href: https://github.com/fire

bibliography: references.bib

format:
  html:
    toc: true
    theme:
      light: flatly
      dark: darkly

filters:
  - quarto
  - filters/decision-meta.py

freeze: true
